### ISSUE TITLE
aUSD and LDOT values not visable

### ISSUE THREAD

**Issue by Elioto0** [AcalaNetwork/acala-dapp#147] opened 2020-07-27 12:48 UTC
Not sure if it's just me but I don't get a full screen and therefore can't see the value amounts for aUSD and LDOT on the dashboard.
![image](https://user-images.githubusercontent.com/67702375/88543185-a2fd4d00-d028-11ea-9780-5f56546f6159.png)

5DkvY7UmPixhDvhSZhAxKn6kDbiNAZpEEPp8xxrGrdNPhNGq

**Comment by qwer951123** [comment] 2020-07-30 11:24
Thanks for your feedback, duplicate of #140, and will be closed.

**Closed by qwer951123** 2020-07-30 11:24 UTC
