### ISSUE TITLE
Balance does not fit into a string

### ISSUE THREAD

**Issue by Madbustazz** [AcalaNetwork/acala-dapp#150] opened 2020-07-27 05:49 UTC
![2020-07-27_10-48-46](https://user-images.githubusercontent.com/53031434/88507816-b4c5fc80-cff6-11ea-914b-e176155e8ccd.png)
Hi! some problem in interface. Thank you!
my wallet 5CADxhweP2DLG1zvdVbUmf9ECPDW8nEETHz32E9E4wBLpxoJ

**Comment by qwer951123** [comment] 2020-07-28 07:14
> I connected from Russia. Or what you mean?

I suppose some location format like toLocalString caused this problem, I removed related code, could you reload this page?

**Comment by Madbustazz** [comment] 2020-07-28 07:16
> > I connected from Russia. Or what you mean?
> 
> I suppose some location format like toLocalString caused this problem, I had removed related code, could you reload this page?

Now all clean! Thank you!
![2020-07-28_12-18-28](https://user-images.githubusercontent.com/53031434/88631753-1a37ed00-d0cc-11ea-9136-b82c6dc37fbf.png)

**Comment by qwer951123** [comment] 2020-08-17 01:19
Duplicate of #144

**Closed by qwer951123** 2020-08-17 01:19 UTC
