### ISSUE TITLE
Swap tab, swap aUSD to aUSD, Incorrect error message

### ISSUE THREAD

**Issue by whoissatoshi** [AcalaNetwork/acala-dapp#193] opened 2020-08-03 13:40 UTC
Step to reproduce:

1.  Login to the wallet.
2.  go to **Swap** tab
3.  select **Pay with** aUSD, select **Receive** aUSD.
4.  Fill filed **Pay with** as "0.1"

Expected result: **Receive** filed is not empty, no error message
Actual result: **Receive** filed is empty and error message is displayed

5F2FNhhVeG9bW4tP5te4a7asBJvSHQg31RzkoETLpUN161gV

![Selection_012](https://user-images.githubusercontent.com/69153826/89188994-0dbe0380-d5a8-11ea-9f45-c1dbc7ef31d1.png)

**Comment by qwer951123** [comment] 2020-08-05 17:47
This is a baned trading pair, we will fix it.

**Comment by qwer951123** [comment] 2020-08-05 18:41
Duplicate of #159

**Closed by qwer951123** 2020-08-05 18:41 UTC
