### ISSUE TITLE
Screen optimization

### ISSUE THREAD

**Issue by fomod-in** [AcalaNetwork/acala-dapp#156] opened 2020-07-28 09:05 UTC
Hello, here some issues on UI. There is not a scrolling window so the interface seems to be "cutted" and not well displayed

![Acala_Platform](https://user-images.githubusercontent.com/67189658/88643566-2323c100-d0c2-11ea-9c9e-794e09c0acbd.png)

![Acala_Platform2](https://user-images.githubusercontent.com/67189658/88643591-2ae36580-d0c2-11ea-806a-dfda6b48568c.png)

Address: 5CmBji31sYE8nBiMXizWCqYqGT9GN8KY5YKMbc2FhTbLKPyK

**Comment by qwer951123** [comment] 2020-07-30 11:25
Thanks for your feedback, duplicate of #140, and will be closed.

**Closed by qwer951123** 2020-07-30 11:25 UTC
