### ISSUE TITLE
Swap tab, swap aUSD to aUSD doesnt work

### ISSUE THREAD

**Issue by whoissatoshi** [AcalaNetwork/acala-dapp#192] opened 2020-08-03 13:34 UTC
System doesnt allow to swap aUSD to aUSD.

Step to reproduce:

1. Login to the wallet.
2. go to **Swap** tab
3. select **Pay with** aUSD, select **Receive** aUSD.
3. Click **MAX** icon on **Pay with**.

Expected result: **Pay with** are not empty filed.
Actual result: **Pay with** empty

5F2FNhhVeG9bW4tP5te4a7asBJvSHQg31RzkoETLpUN161gV

![Selection_011](https://user-images.githubusercontent.com/69153826/89188291-20840880-d5a7-11ea-8006-b647864031ba.png)

**Comment by qwer951123** [comment] 2020-08-05 18:38
This is a baned trading pair, we will fix it.

**Comment by qwer951123** [comment] 2020-08-05 18:40
Duplicate of #159

**Closed** 2020-08-05 18:40 UTC
