### ISSUE TITLE
Self Serviced Loan did not return to the create page after liquidation

### ISSUE THREAD

**Issue by StrawberryFlavor** [AcalaNetwork/acala-dapp#176] opened 2020-07-31 08:54 UTC
After I completed the liquidation, the page did not automatically refresh

Actual page:
![image](https://user-images.githubusercontent.com/28721839/89018300-3945b180-d34e-11ea-93e1-103bd7e9e6fe.png)

Should refresh the resulting page:
![image](https://user-images.githubusercontent.com/28721839/89018395-68f4b980-d34e-11ea-8d68-95ca257f9364.png)

address: 5Coiddko324JRzZpr7yKMEhXhhmEEZS1PL3bW3zuydiiyj1G

**Comment by qwer951123** [comment] 2020-08-17 09:27
Duplicate of #103

**Closed by qwer951123** 2020-08-17 09:27 UTC
