### ISSUE TITLE
Validation rules for swaps

### ISSUE THREAD

**Issue by Mitra8** [AcalaNetwork/acala-dapp#227] opened 2020-08-09 08:06 UTC
The interface allows converting, for example, renBTC to renBTC.
![image](https://user-images.githubusercontent.com/69203809/89727721-07101000-da30-11ea-8afa-504cd6cefeff.png)
However, the transaction failes:
![image](https://user-images.githubusercontent.com/69203809/89727727-18f1b300-da30-11ea-928c-18999f27fbec.png)

Probably, some validation rules would be helpful.

5H985QyVoRZudfw2p6DvmwhdfYob8LkgK4pCZdf9rnioUZUd

**Comment by qwer951123** [comment] 2020-08-17 11:08
Duplicate of #159

**Closed by qwer951123** 2020-08-17 11:08 UTC
